---
- name: Create hosts file
  hosts: all
  become: yes
  tasks:
    - name: Add dev host
      lineinfile:
        path: /etc/hosts
        line: "76.223.54.146 dev.kelasdevops.xyz"
        state: present

    - name: Add prod host
      lineinfile:
        path: /etc/hosts
        line: "13.248.169.48 prod.kelasdevops.xyz"
        state: present
